logging:
    file: castile.log

game:
    fullscreen: false
    init:
        season: "spring3"
        map:
            rows: 10
            columns: 16
        character:
            coordinates: "1:6"
            energy: 50
            food: 50
            water: 50
            mutation-resistance: 50
            inspiration: 50
        castile:
            coordinates: "1:7"
            size:
                rows: 3
                columns: 4
    objects:
        descriptors: "classpath*:/descriptors/*.json"
        loot: "classpath*:/loot/*.json"
        lootMapping: "classpath*:/loot-mapping/*.json"
        images: "classpath*:/images/*.png"
    resources:
        food:
            init: 512
            spending: "1,1,1,3"
        water:
            init: 512
            spending: "1,3,1,1"
        mutRes:
            init: 512
            spending: "3,1,3,1"
        inspiration:
            init: 512
            spending: "0,0,0,0"