logging:
    file: castile.log

game:
    fullscreen: false
    init:
        season: "spring3"
        map:
            rows: 10
            columns: 16
        character:
            coordinates: "1:6"
            energy: 50
            food: 512
            water: 512
            mutation-resistance: 512
            inspiration: 512
        castile:
            coordinates: "1:7"
            size:
                rows: 3
                columns: 4
    objects:
        descriptors: "classpath*:/descriptors/*.json"
        loot: "classpath*:/loot/*.json"
        lootMapping: "classpath*:/loot-mapping/*.json"
        images: "classpath*:/images/*.png"
    resources-spending:
        food: "1,1,1,3"
        water: "1,3,1,1"
        mutRes: "3,1,3,1"
        inspiration: "0,0,0,0"